name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
  repository_dispatch:
    types: [forward-push]
  workflow_dispatch:
    inputs:
      min_doc_ver:
        # actions run ID
        description: 'Please min doc version to build, example: 2.5'
        # Default value if no value is explicitly provided
        default: '2.5'
        # Input has to be provided for the workflow to run
        required: true
env:
  DEFAULT_MIN_DOC_VER: '2.5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Download artifacts from workflow build
      uses: dawidd6/action-download-artifact@v9
      with:
        # Optional, GitHub token
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: build.yml
        workflow_conclusion: success
        branch: dev
        name: wasm
        path: tmp/wasm
        repo: axmolengine/axmol
    
    - name: Build HTML sites
      shell: pwsh
      run: |
        ls -r tmp/wasm
        git clone https://github.com/axmolengine/axmol.git tmp/axmol-src
        git -C tmp/axmol-src checkout dev
        $min_doc_ver = '${{ github.event.inputs.min_doc_ver }}'
        if (!$min_doc_ver) { $min_doc_ver = '${{ env.DEFAULT_MIN_DOC_VER }}'}
        ./build.ps1 tmp/axmol-src tmp/wasm -min_doc_ver $min_doc_ver
    
    # Deploy HTML site to GitHub Pages
    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.AXMOL_DEV_DIST_PAT }}
        external_repository: axmolengine/axmol.dev.dist
        publish_dir: ./dist
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: axmol-pages
        cname: axmol.dev
