name: verify-app

on:
  workflow_dispatch:

jobs:
  win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      shell: pwsh
      run: |
        git clone --branch dev https://github.com/axmolengine/axmol.git
        ./axmol/setup.ps1
        axmol new HelloCpp
        axmol -d HelloCpp
  winuwp:
    # build uwp debug avoid github CI fail with memory issue
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      shell: pwsh
      run: |
        git clone --branch dev https://github.com/axmolengine/axmol.git
        ./axmol/setup.ps1
        axmol new HelloCpp
        axmol -d HelloCpp -p winuwp
  win32-clang:
    runs-on: windows-latest
    env:
      # Test winsdk < 10.0.22000.0 (missing C11 standard stdalign.h), axmol will auto fallback to C99 for resolving compiling issue.
      WINSDK_VER: '10.0.19041.0'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      shell: pwsh
      run: |
        git clone --branch dev https://github.com/axmolengine/axmol.git
        ./axmol/setup.ps1
        axmol new HelloCpp
        axmol -d HelloCpp -cc clang
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install deps
      run: |
        git clone --branch dev https://github.com/axmolengine/axmol.git
        echo -e "y" | pwsh ./axmol/setup.ps1
    - name: Build
      shell: pwsh
      run: |
        axmol new HelloCpp
        axmol -d HelloCpp
  osx-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      shell: pwsh
      run: |
        git clone --branch dev https://github.com/axmolengine/axmol.git
        ./axmol/setup.ps1
        axmol new HelloCpp
        axmol -d HelloCpp
  osx-x64:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      shell: pwsh
      run: |
        git clone --branch dev https://github.com/axmolengine/axmol.git
        ./axmol/setup.ps1
        axmol new HelloCpp
        axmol -d HelloCpp
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      shell: pwsh
      run: |
        git clone --branch dev https://github.com/axmolengine/axmol.git
        ./axmol/setup.ps1
        axmol new HelloCpp
        axmol -p android -d HelloCpp
  ios:
    runs-on: macos-latest
    strategy:
      matrix:
        target_os:
          - ios
          - tvos
    env:
      TARGET_OS: ${{ matrix.target_os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      shell: pwsh
      run: |
        git clone --branch dev https://github.com/axmolengine/axmol.git
        ./axmol/setup.ps1
        axmol new HelloCpp
        axmol -p $env:TARGET_OS -a x64 -d HelloCpp
  wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      shell: pwsh
      run: |
        git clone --branch dev https://github.com/axmolengine/axmol.git
        ./axmol/setup.ps1
        axmol new HelloCpp
        axmol -p wasm -d HelloCpp
